const words = ["FAE","HEX","VOW","AEON","ANKH","AURA","BANE","CULT","FATE","ICON","LICH","MAGE","MOON","OMEN","PACT","RITE","RUNE","SCRY","SEAL","SEER","SOUL","VOID","WAND","WYRM","ABYSS","ADEPT","ALTAR","ANGEL","ARIES","AZOTH","BESOM","BLOOD","BROOM","CABAL","CHARM","CODEX","COVEN","CURSE","DEITY","DEMON","DRUID","EARTH","ESBAT","EVOKE","FOCUS","KARMA","LUNAR","MUDRA","NEXUS","POWER","RAVEN","REALM","RELIC","RUNIC","SIGIL","SKULL","SOLAR","SPELL","STAFF","TAROT","TOTEM","UMBRA","VENUS","VIGIL","WICCA","WITCH","ABJURE","AETHER","ALBEDO","AMULET","ANOINT","ARCANA","ARCHON","ASPECT","ASTRAL","AUGURY","AVATAR","BANISH","BOLINE","CENSER","CHAKRA","CIRCLE","DAEMON","DAGGER","ELIXIR","ENTITY","GNOSIS","GORGON","HALLOW","HOODOO","INVOKE","KARMIC","KISMET","MAGICK","MANTRA","MEDIUM","MIRROR","MYSTIC","OCCULT","ORACLE","ORISON","POTION","PURIFY","RITUAL","ROSARY","SABBAT","SACRED","SATURN","SCARAB","SEANCE","SERAPH","SHADOW","SPHERE","SPIRIT","SULFUR","SUMMON","SYMBOL","TABLET","TEMPLE","TRANCE","UNBIND","VANISH","VELLUM","VESSEL","VISION","VORTEX","VOTIVE","WIZARD","WRAITH","ZENITH","ZODIAC","ALCHEMY","ANGELIC","BINDING","BRAZIER","CALCINE","CAMBION","CHALICE","CHANNEL","CONJURE","CRYSTAL","DOWSING","ECLIPSE","ELEMENT","EQUINOX","ESSENCE","FORMULA","FORTUNE","GATEWAY","INCENSE","LEYLINE","LITURGY","MANDALA","MERCURY","MYSTERY","OBELISK","PHANTOM","PHOENIX","PSYCHIC","REBIRTH","SANCTUM","SCEPTER","SCRYING","SERPENT","SORCERY","THEURGY","VAMPIRE","WARDING","WARLOCK","ABLUTION","AETHERIC","ALKAHEST","AMETHYST","ANATHEMA","ANTIMONY","BALEFIRE","BAPHOMET","BASILISK","BLESSING","CADUCEUS","CAULDRON","CEREMONY","CONCLAVE","CONJURER","COVENANT","CRUCIBLE","ELDRITCH","ENOCHIAN","ETHEREAL","EXORCISE","FAMILIAR","GEMSTONE","GRIMOIRE","HERMETIC","INITIATE","KABBALAH","MAGICIAN","MAGISTER","MANIFEST","OBLATION","OBSIDIAN","PANTHEON","PENDULUM","PENTACLE","PROPHECY","SERVITOR","SOLSTICE","SORCERER","TINCTURE","ANCESTRAL","ARCHANGEL","ARSGOETIA","ASCENSION","BANISHING","BLASPHEMY","BRIMSTONE","CATACOMBS","CELESTIAL","FORBIDDEN","HOROSCOPE","LABYRINTH","LODESTONE","OUROBOROS","PALMISTRY","PYROMANCY","SACRIFICE","TRANSMUTE","VIBRATION","XYLOMANCY","APOTHECARY","APOTHEOSIS","APPARITION","BELLADONNA","CONSECRATE","DIVINATION","HIEROPHANT","INVOCATION","NECROMANCY","NUMEROLOGY","PLANCHETTE","POSSESSION","PROTECTION","UNDERWORLD","BENEDICTION","BIBLIOMANCY","ENCHANTMENT","ENCHANTRESS","INCANTATION","MALEDICTION","NECROMANCER","POLTERGEIST","QUICKSILVER","WIDDERSHINS","CLAIRVOYANCE","COUNTERSPELL","QUINTESSENCE","RESURRECTION","CLAIRAUDIENCE","CONSTELLATION","METAMORPHOSIS"];

const details = [];
for (const base of words) {
  let subwords = [];
  const baseCounts = {};
  for (const char of base) baseCounts[char] = (baseCounts[char] || 0) + 1;
  
  for (const word of words) {
    if (word === base) continue;
    let canForm = true;
    const wordCounts = {};
    for (const char of word) wordCounts[char] = (wordCounts[char] || 0) + 1;
    for (const char in wordCounts) {
      if (!baseCounts[char] || baseCounts[char] < wordCounts[char]) {
        canForm = false;
        break;
      }
    }
    if (canForm) subwords.push(word);
  }
  details.push({ base, count: subwords.length, subwords });
}
details.sort((a, b) => b.count - a.count);
console.log("Top 20 bases by subword count:");
for (let i = 0; i < 20; i++) {
  console.log(`${details[i].base}: ${details[i].count} subwords (${details[i].subwords.join(', ')})`);
}
console.log("Number of bases with 0 subwords:", details.filter(d => d.count === 0).length);
